my_site/urls.py
from django.contrib import admin
from django.urls import path, include
from p_library import views
from p_library.views import AuthorEdit, AuthorList, author_create_many, books_authors_create_many

urlpatterns = [
    path('p_library/', include('p_library.urls', namespace='p_library')),
    path('admin/', admin.site.urls),
    path('', views.books_list),
    path('index/', views.index),
    path('index/book_increment/', views.book_increment),
    path('index/book_decrement/', views.book_decrement),
    path('editors/', views.editors),
    path('authors', AuthorList.as_view(), name='author_list'),
    path('author/create', AuthorEdit.as_view(), name='author_create'),
    path('author/create_many', author_create_many, name='author_create_many'),
    path('author_book/create_many', author_create_many, name='author_book_create_many'),
    path('friends/', views.FriendList.as_view(), name='friend_list'),
    path('friends/create', views.FriendCreate.as_view(), name='friend_create'),
]
app_name = 'p_library'

p_library/urls.py
from django.urls import path  
from .views import AuthorEdit, AuthorList, author_create_many, books_authors_create_many, FriendList, FriendCreate
  
app_name = 'p_library'  
urlpatterns = [  
    path('author/create', AuthorEdit.as_view(), name='author_create'),  
    path('authors', AuthorList.as_view(), name='author_list'),
    path('author/create_many', author_create_many, name='author_create_many'),
    path('author_book/create_many', author_create_many, name='author_book_create_many'),
    path('friends/', FriendList.as_view(), name='friend_list'),
    path('friends/create', FriendCreate.as_view(), name='friend_create'),
]

p_library/models.py
from django.db import models

# Create your models here.
from django.db import models  

class Author(models.Model):  
    full_name = models.TextField()  
    birth_year = models.SmallIntegerField()  
    country = models.CharField(max_length=2)

    def __str__(self):  
        return "{},{}".format(self.full_name,self.birth_year)

class Book(models.Model):  
    ISBN = models.CharField(max_length=13)  
    title = models.TextField()  
    description = models.TextField()  
    year_release = models.SmallIntegerField()  
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    copy_count = models.SmallIntegerField()
    price = models.DecimalField(max_digits=15, decimal_places=2)
    editor = models.ForeignKey('Editor', on_delete=models.CASCADE,null=True,blank=True,related_name='books')
    friend = models.ForeignKey('Friend', on_delete=models.CASCADE,null=True,blank=True)

    def __str__(self):
        return self.title

class Editor(models.Model):
    name = models.CharField(max_length=128)

    def __str__(self):
        return self.name

class Friend(models.Model):
    full_name = models.TextField()
    
    def __str__(self):
        return self.full_name

p_library/forms.py
from django import forms  
from p_library.models import Author, Book, Friend
  
class AuthorForm(forms.ModelForm):  
    full_name = forms.CharField(widget=forms.TextInput)    
    class Meta:  
        model = Author  
        fields = '__all__'

class BookForm(forms.ModelForm):  
    class Meta:  
        model = Book  
        fields = '__all__'

class FriendForm(forms.ModelForm):  

    full_name = forms.CharField(widget=forms.TextInput)

    class Meta:  
        model = Friend  
        fields = '__all__'

p_library/views.py
from django.shortcuts import render, redirect
from p_library.models import Book, Editor, Friend
from django.http import HttpResponse
from django.template import loader
from p_library.models import Author  
from p_library.forms import AuthorForm, BookForm, FriendForm
from django.views.generic import CreateView, ListView
from django.urls import reverse_lazy
from django.forms import formset_factory  
from django.http.response import HttpResponseRedirect

# Create your views here.
def books_list(request):
    books = Book.objects.all()
    return HttpResponse(books)

def index(request):
    template = loader.get_template('index.html')
    books = Book.objects.all()
    biblio_data = {
        "title": "мою библиотеку",
        "books": books,
    }
    return HttpResponse(template.render(biblio_data, request))

def book_increment(request):
    if request.method == 'POST':
        book_id = request.POST['id']
        if not book_id:
            return redirect('/index/')
        else:
            book = Book.objects.filter(id=book_id).first()
            if not book:
                return redirect('/index/')
            book.copy_count += 1
            book.save()
        return redirect('/index/')
    else:
        return redirect('/index/')

def book_decrement(request):
    if request.method == 'POST':
        book_id = request.POST['id']
        if not book_id:
            return redirect('/index/')
        else:
            book = Book.objects.filter(id=book_id).first()
            if not book:
                return redirect('/index/')
            if book.copy_count < 1:
                book.copy_count = 0
            else:
                book.copy_count -= 1
            book.save()
        return redirect('/index/')
    else:
        return redirect('/index/')

def editors(request):
    template = loader.get_template('editors.html')
    editors = Editor.objects.all()
    data ={
        "editors":editors,
    }
    return HttpResponse(template.render(data,request))

class AuthorEdit(CreateView):  
    model = Author  
    form_class = AuthorForm  
    success_url = reverse_lazy('p_library:author_list')  
    template_name = 'author_edit.html'  

class AuthorList(ListView):  
    model = Author  
    template_name = 'authors_list.html'

class FriendCreate(CreateView):
    model = Friend
    form_class = FriendForm
    success_url = reverse_lazy('p_library:friend_list')
    template_name = 'friend_edit.html'

class FriendList(ListView):
    model = Friend
    template_name = 'friend_list.html'

def author_create_many(request):  
    AuthorFormSet = formset_factory(AuthorForm, extra=2)  #  Первым делом, получим класс, который будет создавать наши формы. Обратите внимание на параметр `extra`, в данном случае он равен двум, это значит, что на странице с несколькими формами изначально будет появляться 2 формы создания авторов.
    if request.method == 'POST':  #  Наш обработчик будет обрабатывать и GET и POST запросы. POST запрос будет содержать в себе уже заполненные данные формы
        author_formset = AuthorFormSet(request.POST, request.FILES, prefix='authors')  #  Здесь мы заполняем формы формсета теми данными, которые пришли в запросе. Обратите внимание на параметр `prefix`. Мы можем иметь на странице не только несколько форм, но и разных формсетов, этот параметр позволяет их отличать в запросе.
        if author_formset.is_valid():  #  Проверяем, валидны ли данные формы
            for author_form in author_formset:  
                author_form.save()  #  Сохраним каждую форму в формсете
            return HttpResponseRedirect(reverse_lazy('p_library:author_list'))  #  После чего, переадресуем браузер на список всех авторов.
    else:  #  Если обработчик получил GET запрос, значит в ответ нужно просто "нарисовать" формы.
        author_formset = AuthorFormSet(prefix='authors')  #  Инициализируем формсет и ниже передаём его в контекст шаблона.
    return render(request, 'manage_authors.html', {'author_formset': author_formset})

def books_authors_create_many(request):  
    AuthorFormSet = formset_factory(AuthorForm, extra=2)  
    BookFormSet = formset_factory(BookForm, extra=2)  
    if request.method == 'POST':  
        author_formset = AuthorFormSet(request.POST, request.FILES, prefix='authors')  
        book_formset = BookFormSet(request.POST, request.FILES, prefix='books')  
        if author_formset.is_valid() and book_formset.is_valid():  
            for author_form in author_formset:  
                author_form.save()  
            for book_form in book_formset:  
                book_form.save()  
            return HttpResponseRedirect(reverse_lazy('p_library:author_list'))  
    else:  
        author_formset = AuthorFormSet(prefix='authors')  
        book_formset = BookFormSet(prefix='books')  
    return render(
	    request,  
		'manage_books_authors.html',  
		{  
	        'author_formset': author_formset,  
			'book_formset': book_formset,  
		}  
	)

def borrowed_book(request):
    if request.method == 'POST':
        book_id = request.POST['id']
        friend_id = request.POST['select_borrowed']
        if not book_id:
            return redirect('/index/')
        else:
            book = Book.objects.filter(id=book_id).first()
            friend = Friend.objects.get(id=friend_id)
            if not book:
                return redirect('/index/')
            if book.copy_count < 1:
                book.copy_count = 0
            else:
                book.copy_count -= 1
                book.borrowed_book_count += 1
                book.friend.add(friend)
            book.save()
        return redirect('/index/')
    else:
        return redirect('/index/')

def returned_book(request):
    if request.method == 'POST':
        book_id = request.POST['id']
        friend_id = request.POST['select_returned']
        if not book_id:
            return redirect('/index/')
        else:
            book = Book.objects.filter(id=book_id).first()
            friend = Friend.objects.get(id=friend_id)
            if not book:
                return redirect('/index/')
            if book.borrowed_book_count < 1:
                book.borrowed_book_count = 0
            else:
                book.copy_count += 1
                book.borrowed_book_count -= 1
                book.friend.remove(friend)
            book.save()
        return redirect('/index/')
    else:
        return redirect('/index/')

p_library/templates/author_edit.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
	<meta charset="UTF-8">  
	<title>Форма создания и редактирования Авторов</title>  
</head>  
<body>  
<form method="post">  
	{% csrf_token %}  
	{{ form.as_p }}  
	<input type="submit" value="Сохранить">  
</form>  
</body>  
</html>

p_library/templates/authors_list.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Список авторов</title>
</head>
<body>
	<ul>
		{% for author in object_list %}
		    <li>{{ author.full_name }}</li>
		{% endfor %}
	</ul>
</body>

p_library/templates/editors.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Title</title>
</head>
<body>
    {% for editor in editors %}
        <ul class="list-group">
            <li class="list-group-item">
                {{ editor.name }}
                <ul class="list-group">
                    {% for book in editor.books.all %}
                        <li class="list-group-item"> {{ book.title }}</li>
                    {% endfor %}
                </ul>
            </li>
        </ul>
    {% endfor %}
</body>
</html>

p_library/templates/friend_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Форма создания и редактирования друзей</title>
</head>
<body>
    <div class="container">
        <div class="col-12 my-3">
            <h2 class="text-center my-3">Форма создания и редактирования друзей:</h2>
            <form method="post"> 
                {% csrf_token %}
                {{ form.as_p }}
                <input class="btn btn-success my-3" type="submit" value="Сохранить">
                <a class="btn btn-danger my-3" href="{%url 'p_library:friend_list'%}">Отмена</a>
            </form>
        </div>  
    </div>
</body>
</html>

p_library/templates/friend_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Список друзей</title>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-12 my-3">
                <h2 class="text-secondary text-center my-3">Список друзей:</h2>
                <table class="table table-dark table-stripped table-hover">
                    {% for friend in object_list %}
                    <tr class="table-bordered">
                        <td style="width:20px;">{{ forloop.counter }}</td>
                        <td>{{ friend.full_name }}</td>
                    </tr>
                    {% endfor %}
                </table>
                <a class="btn btn-success my-3" href="{%url 'p_library:friend_create'%}">Добавить друга</a>
            </div>
        </div>
    </div>
</body>
</html>

p_library/templates/index.html
Добро пожаловать в {{ title }}  <br>.
Тут собрано {{ books|length }} книг из моей личной коллекции.

<table border="1">
    {% for book in books %}
        <tr>
            <td>{{ book.title }}</td>
            <td>{{ book.ISBN }}</td>
            <td>{{ book.description }}</td>
            <td>{{ book.year_release }}</td>
            <td>{{ book.author.full_name }}</td>
            <td>{{ book.author.country }}</td>
            <td>{{ book.copy_count }}</td>
            <td>
                <form action="/index/book_increment/" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <input type="hidden" name="id" value="{{book.id}}" />
                    <input type="submit" value="Увеличить кол-во" />
                </form>
                <form action="/index/book_decrement/" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <input type="hidden" name="id" value="{{book.id}}" />
                    <input type="submit" value="Уменьшить кол-во" />
                </form>
            </td>
        </tr>
    {% endfor %}
</table>

p_library/templates/manage_authors.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
 <meta charset="UTF-8">  
 <title>Create multiple authors</title>  
</head>  
<body>  
<form method="post">  
	{% csrf_token %}  
	{% for form in author_formset %}  
		{{ form.as_ul }}  
		<br>  
	{% endfor %}
    <input type="submit" value="Сохранить"/>  
</form>  
</body>  
</html>

p_library/templates/manage_books_authors.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
 <meta charset="UTF-8">  
 <title>Create multiple Authors and Books</title>  
</head>  
<body>  
<form method="post">  
  {% csrf_token %}  
  {% for form in author_formset %}  
        {{ form.as_ul }}  
        <br>  
  {% endfor %}  
  
    {% for form in book_formset %}  
        {{ form.as_ul }}  
        <br>  
  {% endfor %}  
    <input type="submit" value="Сохранить"/>  
</form>  
</body>  
</html>